### ISSUE TITLE
Documentation 0.6

### ISSUE THREAD

**Issue by stefanwalther** [stefanwalther/sense-go#23]
**Concepts:**
- [x] Installation
- [x] Deployment
- [x] Configuration
- [x] Overall workflow
- [x] Task chains

**Tasks:**
- [x] bump
- [x] clean
- [x] copy
- [x] ~~git~~ - actually not sure if really useful
- [x] htmlmin
- [x] import
- [x] ~~jsonlint~~ - It's there, but let's document it later, not really MVP
- [x] jsonminify
- [x] less
- [x] ~~npm~~ - It's there, but let's document it later, not really MVP
- [x] replace
- [x] ssh
- [x] ~~transpile~~ - actually not sure if really useful, so removed from doc
- [x] uglify
- [x] wbfolder
- [x] zip
- [x] watch
